# SITE CONFIGURATION
title: Manikanth P # your site title
name: Manikanth P
author: GitHub User # You :P
description: > # Meta description of Homepage
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://manikanthp.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social: 
  name: Manikanth P
  links:
    - https://twitter.com/manikanthgoud3
    - https://www.facebook.com/manikanthgoud559
    - https://www.linkedin.com/in/manikanth123
    - https://plus.google.com/+manikanthgoud123
    - https://github.com/manikanthp

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Blogs', link: '/blogs'}
  - {name: 'Projects', link: '/projects'}
  - {name: 'Research', link: '/research'}
  - {name: 'LLM Course', link: '/LLM_course'}
  - {name: 'About', link: '/about'}

  
tagline: >
  Hi I am Manikanth, and this is my website! Here you can find some of my works and blogs. If you have any question, feel free to get in touch.

hero_img: posts/intro_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: manikanthgoud123@gmail.com # email for form submission

twitter_username: manikanthgoud3 # replace with your_twitter_username or comment to remove link from footer
github_username:  manikanthp # replace with your_github_username or comment to remove link from footer
instagram_username: '' # replace with your_instagram_username or comment to remove link from footer
medium_username: manikanthgoud123
kaggle_username: manikanthgoud
disqus: 
  shortname: manikanth # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title

compress_html:
  clippings: all


collections:
  sections:
    sort_by: date
    output: true
    permalink: :title
  projects_done:
    sort_by: date
    output: true 
    permalink: :title
  
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
